### ISSUE TITLE
MSBuildにしたい

### ISSUE THREAD

**Issue by takanakahiko** [takanakahiko/MovieOnWallpaper#3]
VisualStudio対象外から失礼するゾ～（謝罪）このコンパイルオプション長スギィ！！！！自分、MSBuildいいっすか？ C#知ってそうだからオタクのリストにぶち込んでやるぜー いきなりissueしてすみません！許してください！なんでもしますから！(なんでもするとは言ってない)

**Comment by prprhyt** [comment]
MS BuildってVisual Studioから読み込めるようになってればいいんすか?  
それなら自分、できましたよ兄貴

**Comment by prprhyt** [comment]
#5 どうっすか

**Comment by takanakahiko** [comment]
や、msBuildはコマンドから打つのを想定しています。(というかぼくの環境にVisualStudioが無いので許して)

**Comment by takanakahiko** [comment]
参考 : https://msdn.microsoft.com/ja-jp/library/ms171452(v=vs.90).aspx

**Comment by prprhyt** [comment]
62a8fa5 でmsbuildコマンドに対応しますた。
322c355 msbuildの方法に変更したのをREADMEに載せた

**Comment by prprhyt** [comment]
#7 にMSBuildも含まれているので、#7 をマージするなら #5 はマージしなくて大丈夫です

**Comment by takanakahiko** [comment]
#7 のマージ時に #5 も同時にマージされました。仕様らしい。
ありがとうございます。
