### ISSUE TITLE
Formの座標指定が効いて無い

### ISSUE THREAD

**Issue by prprhyt** [takanakahiko/MovieOnWallpaper#6]
マルチディスプレイで接続すると確認できた。  
this.Left = this.Top = 0 が効いて無いっぽくて表示がずれる。  
https://github.com/takanakahiko/MovieOnWallpaper/blob/a20ad98b489984ce898f89bb9e0ea0c101c0b013/Program.cs#L56

**Comment by prprhyt** [comment]
#7 9022373 これで修正済み

**Comment by takanakahiko** [comment]
マージしました
